### PR TITLE
Used to fixes #62

### LINKED ISSUE #62: There is a stupid gcc issue that affect DirectX-Headers
https://news.russellsaw.io/article?id=art_4qfDEhAdkMA

### PR DESCRIPTION
**Pull request by lygstate**
The wgl tests and clc tests under msys2 are working,
Linux/mingw wine need investigate

Fixes #62

### CODE REVIEW

**Review by jenatali — CHANGES_REQUESTED** [review]
Sorry, no. These are Windows SDK headers intended for targeting D3D12 in Windows and WSL. Anything else is out of scope here. An equivalent parallel project could be set up with a directory structure such that it can be a drop-in replacement for Mesa, but it does not belong here. Compiling with MinGW to target Windows is one thing (and is honestly questionable already since MinGW has its own SDK headers), but targeting the MSYS2 runtime environment is different and not a contribution this project is looking for.

**Comment by walbourn** [comment]
Removing the SAL annotation from the API is not an option as Jesse notes. Note that you can already easily solve this issue by using the open-source version of ``sal.h`` obtained from: https://raw.githubusercontent.com/dotnet/corert/master/src/Native/inc/unix/sal.h.

In fact, the vcpkg DirectXMath port will automatically add this file for Linux scenarios.

**Comment by lygstate** [comment]
> Removing the SAL annotation from the API is not an option as Jesse notes. Note that you can already easily solve this issue by using the open-source version of `sal.h` obtained from: https://raw.githubusercontent.com/dotnet/corert/master/src/Native/inc/unix/sal.h.
> 
> In fact, the vcpkg DirectXMath port will automatically add this file for Linux scenarios.

It's a temp hack, doing this is beccause MIDL can not generate `ABI` fixes for gnu, the rational is at 
https://news.russellsaw.io/article?id=art_4qfDEhAdkMA
And microsoft's MIDL is not opensource, so I am not table to update MIDL to do that

**Comment by lygstate** [comment]
> Removing the SAL annotation from the API is not an option as Jesse notes. Note that you can already easily solve this issue by using the open-source version of `sal.h` obtained from: https://raw.githubusercontent.com/dotnet/corert/master/src/Native/inc/unix/sal.h.
> 
> In fact, the vcpkg DirectXMath port will automatically add this file for Linux scenarios.

Specifically, automatically generating something like this:
```c
#ifdef WIDL_EXPLICIT_AGGREGATE_RETURNS
    virtual D3D12_CPU_DESCRIPTOR_HANDLE* STDMETHODCALLTYPE GetCPUDescriptorHandleForHeapStart(D3D12_CPU_DESCRIPTOR_HANDLE *__ret) = 0;
    D3D12_CPU_DESCRIPTOR_HANDLE STDMETHODCALLTYPE GetCPUDescriptorHandleForHeapStart()
    {
        D3D12_CPU_DESCRIPTOR_HANDLE __ret;
        return *GetCPUDescriptorHandleForHeapStart(&__ret);
    }
#else
    // We crash here!
    virtual D3D12_CPU_DESCRIPTOR_HANDLE STDMETHODCALLTYPE GetCPUDescriptorHandleForHeapStart() = 0;
#endif
```

**Comment by jenatali** [comment]
I realized I was a bit wrong about what this accomplishes - this enables using MinGW to target Windows with C++. Without this, only the C interface in MinGW matches the DLL.

I'll put it on my backlog to dig into MIDL (again) to see about adding some cross-platform compatibility here. We'll want to be able to have implementers and callers across the matrix of {Windows ABI (return structs by pointer), Linux ABI (return structs by value)} and {C++, C}.

As-is, the C++ ABI is always native to the compiler while the C ABI is always Windows. So MinGW compiling GLOn12 is broken since the caller is using the Linux ABI (since it's C++) but the implementer is using the Windows ABI, and also Dozen is broken in WSL since the implementer is using the Linux ABI (C++) but the caller is using the Windows ABI (since it's C).

I think we'll need macros for both sides to indicate whether we want the C++ and C interfaces to return the structs directly or use the hidden pointer approach. For Windows (MSVC), both C++ definitions would be identical, but having the option would allow a MinGW caller/implementer to work.

However this PR is not acceptable. We're not removing SAL from the Windows IDLs just so WIDL can run on them, and we're not adding GNU/MinGW variations of headers to the Windows SDK headers. I'll close this PR and follow up in the future with updated headers from MIDL changes.

**Comment by lygstate** [comment]
> I think we'll need macros for both sides to indicate whether we want the C++ and C interfaces to return the structs directly or use the hidden pointer approach. For Windows (MSVC), both C++ definitions would be identical, but having the option would allow a MinGW caller/implementer to work.

Thanks, this is just a try to fixes the mesa issue, not a good way to do that, to fixes it properly,  may be in MIDL

**Pull request closed without merging**
