### PR TITLE
I create a fork of widl to genreate header files that compat both msvc/gcc

### PR DESCRIPTION
**Pull request by lygstate**
The for of wmidl are  here:
https://github.com/win-polyfill/wmidl.git,

By doing this, it's makes the header files are directly support of operator __uuidof and simplified the codes a lot,
`dxguids.h` can be simplified future, but I leave it behind to discuss first

### CODE REVIEW

**Comment by jenatali** [comment]
I think you need to take a step back and explain why you're doing this. Clearly you've put in a lot of work to get the Mesa `d3d12` and `dozen` components building with MinGW... but why? If you're going to run on Windows, why not just build on Windows? Or if you need to cross-compile, why not use clang which can compile the Windows SDK headers directly? What's the reason that it needs to be MinGW?

**Comment by lygstate** [comment]
> I think you need to take a step back and explain why you're doing this. Clearly you've put in a lot of work to get the Mesa `d3d12` and `dozen` components building with MinGW... but why? If you're going to run on Windows, why not just build on Windows? Or if you need to cross-compile, why not use clang which can compile the Windows SDK headers directly? What's 
Sorry, there is no toolchain under linux can using windows sdk yet,  at least I didn't see yet, if there is such toolchain, that's would be good:)

Sorry  for pushing the wrong code, the PR is not only intent to fixes compiling with MINGW, but also used to fixes #62,
besides, It's can now implement __uuidof operator with gcc(linux) properly, by doing this we can greatly simplify the header
`dxguids.h` and goes future to by removing `WINADAPTER_IID` and related defines.

**Comment by jenatali** [comment]
> Sorry, there is no toolchain under linux can using windows sdk yet, at least I didn't see yet, if there is such toolchain, that's would be good:)

Ah maybe I'm wrong, I could've sworn that the case-sensitivity changes that had happened were for the purpose of letting the Windows SDK be used when cross-compiling from Linux. I know Clang can build Windows code, so the only problem would be the direction of slashes and case sensitivity, and I thought we'd cleaned most of those up - or I think Clang might have compatibility options for them.

But yeah, the SDK still has to be installed on Windows, it can't be installed directly in Linux, so I guess that still makes it a non-starter.

**Review by jenatali — CHANGES_REQUESTED** [review]
Sorry, but this is still a no. This repo is, and always will be, a mirror of the Windows SDK headers. Those headers will always be produced by MIDL.

For the purpose of making things work in Mesa, feel free to host a fork. You can update the Mesa CI pipelines to clone, build, and install the fork.

**Comment by jenatali** [comment]
Closing this. The headers now have appropriate `#ifdef` blocks which should allow MinGW to target the MSVC C++ ABI.

**Pull request closed without merging**
